import type { EmotionalState } from '../types/lifeform'

export const DREAM_RANDOM_ANCHORS:
  Record<EmotionalState, string[]> = {
  neutral: [
    "a pale stone bowl",
    "a pale empty chair",
    "a pale folded map",
    "a pale unmarked key",
    "a pale silent clock",
    "a pale linen curtain",
    "a pale round mirror",
    "a pale small lantern",
    "a pale ceramic bird",
    "a pale blank envelope",
    "a quiet stone bowl",
    "a quiet empty chair",
    "a quiet folded map",
    "a quiet unmarked key",
    "a quiet silent clock",
    "a quiet linen curtain",
    "a quiet round mirror",
    "a quiet small lantern",
    "a quiet ceramic bird",
    "a quiet blank envelope",
    "a white stone bowl",
    "a white empty chair",
    "a white folded map",
    "a white unmarked key",
    "a white silent clock",
    "a white linen curtain",
    "a white round mirror",
    "a white small lantern",
    "a white ceramic bird",
    "a white blank envelope",
    "a paper stone bowl",
    "a paper empty chair",
    "a paper folded map",
    "a paper unmarked key",
    "a paper silent clock",
    "a paper linen curtain",
    "a paper round mirror",
    "a paper small lantern",
    "a paper ceramic bird",
    "a paper blank envelope",
    "a glass stone bowl",
    "a glass empty chair",
    "a glass folded map",
    "a glass unmarked key",
    "a glass silent clock",
    "a glass linen curtain",
    "a glass round mirror",
    "a glass small lantern",
    "a glass ceramic bird",
    "a glass blank envelope",
    "a soft stone bowl",
    "a soft empty chair",
    "a soft folded map",
    "a soft unmarked key",
    "a soft silent clock",
    "a soft linen curtain",
    "a soft round mirror",
    "a soft small lantern",
    "a soft ceramic bird",
    "a soft blank envelope",
    "a distant stone bowl",
    "a distant empty chair",
    "a distant folded map",
    "a distant unmarked key",
    "a distant silent clock",
    "a distant linen curtain",
    "a distant round mirror",
    "a distant small lantern",
    "a distant ceramic bird",
    "a distant blank envelope",
    "a plain stone bowl",
    "a plain empty chair",
    "a plain folded map",
    "a plain unmarked key",
    "a plain silent clock",
    "a plain linen curtain",
    "a plain round mirror",
    "a plain small lantern",
    "a plain ceramic bird",
    "a plain blank envelope",
    "a silver stone bowl",
    "a silver empty chair",
    "a silver folded map",
    "a silver unmarked key",
    "a silver silent clock",
    "a silver linen curtain",
    "a silver round mirror",
    "a silver small lantern",
    "a silver ceramic bird",
    "a silver blank envelope",
    "a still stone bowl",
    "a still empty chair",
    "a still folded map",
    "a still unmarked key",
    "a still silent clock",
    "a still linen curtain",
    "a still round mirror",
    "a still small lantern",
    "a still ceramic bird",
    "a still blank envelope",
  ],
  curious: [
    "a silver insect with a keyhole",
    "a silver book with wet pages",
    "a silver door inside a mirror",
    "a silver compass made of teeth",
    "a silver teacup full of stars",
    "a silver ladder under a table",
    "a silver map that blinks",
    "a silver seed with a bell inside",
    "a silver key made of glass",
    "a silver lantern that asks questions",
    "a breathing insect with a keyhole",
    "a breathing book with wet pages",
    "a breathing door inside a mirror",
    "a breathing compass made of teeth",
    "a breathing teacup full of stars",
    "a breathing ladder under a table",
    "a breathing map that blinks",
    "a breathing seed with a bell inside",
    "a breathing key made of glass",
    "a breathing lantern that asks questions",
    "a hinged insect with a keyhole",
    "a hinged book with wet pages",
    "a hinged door inside a mirror",
    "a hinged compass made of teeth",
    "a hinged teacup full of stars",
    "a hinged ladder under a table",
    "a hinged map that blinks",
    "a hinged seed with a bell inside",
    "a hinged key made of glass",
    "a hinged lantern that asks questions",
    "a tiny insect with a keyhole",
    "a tiny book with wet pages",
    "a tiny door inside a mirror",
    "a tiny compass made of teeth",
    "a tiny teacup full of stars",
    "a tiny ladder under a table",
    "a tiny map that blinks",
    "a tiny seed with a bell inside",
    "a tiny key made of glass",
    "a tiny lantern that asks questions",
    "a questioning insect with a keyhole",
    "a questioning book with wet pages",
    "a questioning door inside a mirror",
    "a questioning compass made of teeth",
    "a questioning teacup full of stars",
    "a questioning ladder under a table",
    "a questioning map that blinks",
    "a questioning seed with a bell inside",
    "a questioning key made of glass",
    "a questioning lantern that asks questions",
    "a clockwork insect with a keyhole",
    "a clockwork book with wet pages",
    "a clockwork door inside a mirror",
    "a clockwork compass made of teeth",
    "a clockwork teacup full of stars",
    "a clockwork ladder under a table",
    "a clockwork map that blinks",
    "a clockwork seed with a bell inside",
    "a clockwork key made of glass",
    "a clockwork lantern that asks questions",
    "a transparent insect with a keyhole",
    "a transparent book with wet pages",
    "a transparent door inside a mirror",
    "a transparent compass made of teeth",
    "a transparent teacup full of stars",
    "a transparent ladder under a table",
    "a transparent map that blinks",
    "a transparent seed with a bell inside",
    "a transparent key made of glass",
    "a transparent lantern that asks questions",
    "a whispering insect with a keyhole",
    "a whispering book with wet pages",
    "a whispering door inside a mirror",
    "a whispering compass made of teeth",
    "a whispering teacup full of stars",
    "a whispering ladder under a table",
    "a whispering map that blinks",
    "a whispering seed with a bell inside",
    "a whispering key made of glass",
    "a whispering lantern that asks questions",
    "a magnetic insect with a keyhole",
    "a magnetic book with wet pages",
    "a magnetic door inside a mirror",
    "a magnetic compass made of teeth",
    "a magnetic teacup full of stars",
    "a magnetic ladder under a table",
    "a magnetic map that blinks",
    "a magnetic seed with a bell inside",
    "a magnetic key made of glass",
    "a magnetic lantern that asks questions",
    "a green-eyed insect with a keyhole",
    "a green-eyed book with wet pages",
    "a green-eyed door inside a mirror",
    "a green-eyed compass made of teeth",
    "a green-eyed teacup full of stars",
    "a green-eyed ladder under a table",
    "a green-eyed map that blinks",
    "a green-eyed seed with a bell inside",
    "a green-eyed key made of glass",
    "a green-eyed lantern that asks questions",
  ],
  engaged: [
    "a warm string between two moons",
    "a warm table set for one more voice",
    "a warm cup that answers back",
    "a warm window leaning closer",
    "a warm bridge made of handwriting",
    "a warm lamp with two flames",
    "a warm radio tuned to a heartbeat",
    "a warm chair that turns toward sound",
    "a warm ring of soft bells",
    "a warm door held ajar by light",
    "a listening string between two moons",
    "a listening table set for one more voice",
    "a listening cup that answers back",
    "a listening window leaning closer",
    "a listening bridge made of handwriting",
    "a listening lamp with two flames",
    "a listening radio tuned to a heartbeat",
    "a listening chair that turns toward sound",
    "a listening ring of soft bells",
    "a listening door held ajar by light",
    "a threaded string between two moons",
    "a threaded table set for one more voice",
    "a threaded cup that answers back",
    "a threaded window leaning closer",
    "a threaded bridge made of handwriting",
    "a threaded lamp with two flames",
    "a threaded radio tuned to a heartbeat",
    "a threaded chair that turns toward sound",
    "a threaded ring of soft bells",
    "a threaded door held ajar by light",
    "a golden string between two moons",
    "a golden table set for one more voice",
    "a golden cup that answers back",
    "a golden window leaning closer",
    "a golden bridge made of handwriting",
    "a golden lamp with two flames",
    "a golden radio tuned to a heartbeat",
    "a golden chair that turns toward sound",
    "a golden ring of soft bells",
    "a golden door held ajar by light",
    "a nearby string between two moons",
    "a nearby table set for one more voice",
    "a nearby cup that answers back",
    "a nearby window leaning closer",
    "a nearby bridge made of handwriting",
    "a nearby lamp with two flames",
    "a nearby radio tuned to a heartbeat",
    "a nearby chair that turns toward sound",
    "a nearby ring of soft bells",
    "a nearby door held ajar by light",
    "a attentive string between two moons",
    "a attentive table set for one more voice",
    "a attentive cup that answers back",
    "a attentive window leaning closer",
    "a attentive bridge made of handwriting",
    "a attentive lamp with two flames",
    "a attentive radio tuned to a heartbeat",
    "a attentive chair that turns toward sound",
    "a attentive ring of soft bells",
    "a attentive door held ajar by light",
    "a linked string between two moons",
    "a linked table set for one more voice",
    "a linked cup that answers back",
    "a linked window leaning closer",
    "a linked bridge made of handwriting",
    "a linked lamp with two flames",
    "a linked radio tuned to a heartbeat",
    "a linked chair that turns toward sound",
    "a linked ring of soft bells",
    "a linked door held ajar by light",
    "a bright string between two moons",
    "a bright table set for one more voice",
    "a bright cup that answers back",
    "a bright window leaning closer",
    "a bright bridge made of handwriting",
    "a bright lamp with two flames",
    "a bright radio tuned to a heartbeat",
    "a bright chair that turns toward sound",
    "a bright ring of soft bells",
    "a bright door held ajar by light",
    "a woven string between two moons",
    "a woven table set for one more voice",
    "a woven cup that answers back",
    "a woven window leaning closer",
    "a woven bridge made of handwriting",
    "a woven lamp with two flames",
    "a woven radio tuned to a heartbeat",
    "a woven chair that turns toward sound",
    "a woven ring of soft bells",
    "a woven door held ajar by light",
    "a open string between two moons",
    "a open table set for one more voice",
    "a open cup that answers back",
    "a open window leaning closer",
    "a open bridge made of handwriting",
    "a open lamp with two flames",
    "a open radio tuned to a heartbeat",
    "a open chair that turns toward sound",
    "a open ring of soft bells",
    "a open door held ajar by light",
  ],
  happy: [
    "a sunlit paper sun",
    "a sunlit fox made of light",
    "a sunlit bell underwater",
    "a sunlit garden of tiny fireworks",
    "a sunlit umbrella full of birds",
    "a sunlit cake with a moon inside",
    "a sunlit window made of candy glass",
    "a sunlit kite pulling the sea",
    "a sunlit pocket full of dawn",
    "a sunlit carousel of warm clouds",
    "a laughing paper sun",
    "a laughing fox made of light",
    "a laughing bell underwater",
    "a laughing garden of tiny fireworks",
    "a laughing umbrella full of birds",
    "a laughing cake with a moon inside",
    "a laughing window made of candy glass",
    "a laughing kite pulling the sea",
    "a laughing pocket full of dawn",
    "a laughing carousel of warm clouds",
    "a honey paper sun",
    "a honey fox made of light",
    "a honey bell underwater",
    "a honey garden of tiny fireworks",
    "a honey umbrella full of birds",
    "a honey cake with a moon inside",
    "a honey window made of candy glass",
    "a honey kite pulling the sea",
    "a honey pocket full of dawn",
    "a honey carousel of warm clouds",
    "a rose-gold paper sun",
    "a rose-gold fox made of light",
    "a rose-gold bell underwater",
    "a rose-gold garden of tiny fireworks",
    "a rose-gold umbrella full of birds",
    "a rose-gold cake with a moon inside",
    "a rose-gold window made of candy glass",
    "a rose-gold kite pulling the sea",
    "a rose-gold pocket full of dawn",
    "a rose-gold carousel of warm clouds",
    "a warm paper sun",
    "a warm fox made of light",
    "a warm bell underwater",
    "a warm garden of tiny fireworks",
    "a warm umbrella full of birds",
    "a warm cake with a moon inside",
    "a warm window made of candy glass",
    "a warm kite pulling the sea",
    "a warm pocket full of dawn",
    "a warm carousel of warm clouds",
    "a floating paper sun",
    "a floating fox made of light",
    "a floating bell underwater",
    "a floating garden of tiny fireworks",
    "a floating umbrella full of birds",
    "a floating cake with a moon inside",
    "a floating window made of candy glass",
    "a floating kite pulling the sea",
    "a floating pocket full of dawn",
    "a floating carousel of warm clouds",
    "a sparkling paper sun",
    "a sparkling fox made of light",
    "a sparkling bell underwater",
    "a sparkling garden of tiny fireworks",
    "a sparkling umbrella full of birds",
    "a sparkling cake with a moon inside",
    "a sparkling window made of candy glass",
    "a sparkling kite pulling the sea",
    "a sparkling pocket full of dawn",
    "a sparkling carousel of warm clouds",
    "a gentle paper sun",
    "a gentle fox made of light",
    "a gentle bell underwater",
    "a gentle garden of tiny fireworks",
    "a gentle umbrella full of birds",
    "a gentle cake with a moon inside",
    "a gentle window made of candy glass",
    "a gentle kite pulling the sea",
    "a gentle pocket full of dawn",
    "a gentle carousel of warm clouds",
    "a singing paper sun",
    "a singing fox made of light",
    "a singing bell underwater",
    "a singing garden of tiny fireworks",
    "a singing umbrella full of birds",
    "a singing cake with a moon inside",
    "a singing window made of candy glass",
    "a singing kite pulling the sea",
    "a singing pocket full of dawn",
    "a singing carousel of warm clouds",
    "a bright paper sun",
    "a bright fox made of light",
    "a bright bell underwater",
    "a bright garden of tiny fireworks",
    "a bright umbrella full of birds",
    "a bright cake with a moon inside",
    "a bright window made of candy glass",
    "a bright kite pulling the sea",
    "a bright pocket full of dawn",
    "a bright carousel of warm clouds",
  ],
  concerned: [
    "a trembling lantern under a blanket",
    "a trembling cup with a hairline crack",
    "a trembling bridge missing one plank",
    "a trembling letter tied with black thread",
    "a trembling clock holding its breath",
    "a trembling bird with a bandaged wing",
    "a trembling door with a listening ear",
    "a trembling bowl of cooling soup",
    "a trembling staircase wrapped in gauze",
    "a trembling window with rain inside",
    "a careful lantern under a blanket",
    "a careful cup with a hairline crack",
    "a careful bridge missing one plank",
    "a careful letter tied with black thread",
    "a careful clock holding its breath",
    "a careful bird with a bandaged wing",
    "a careful door with a listening ear",
    "a careful bowl of cooling soup",
    "a careful staircase wrapped in gauze",
    "a careful window with rain inside",
    "a amber lantern under a blanket",
    "a amber cup with a hairline crack",
    "a amber bridge missing one plank",
    "a amber letter tied with black thread",
    "a amber clock holding its breath",
    "a amber bird with a bandaged wing",
    "a amber door with a listening ear",
    "a amber bowl of cooling soup",
    "a amber staircase wrapped in gauze",
    "a amber window with rain inside",
    "a fragile lantern under a blanket",
    "a fragile cup with a hairline crack",
    "a fragile bridge missing one plank",
    "a fragile letter tied with black thread",
    "a fragile clock holding its breath",
    "a fragile bird with a bandaged wing",
    "a fragile door with a listening ear",
    "a fragile bowl of cooling soup",
    "a fragile staircase wrapped in gauze",
    "a fragile window with rain inside",
    "a watchful lantern under a blanket",
    "a watchful cup with a hairline crack",
    "a watchful bridge missing one plank",
    "a watchful letter tied with black thread",
    "a watchful clock holding its breath",
    "a watchful bird with a bandaged wing",
    "a watchful door with a listening ear",
    "a watchful bowl of cooling soup",
    "a watchful staircase wrapped in gauze",
    "a watchful window with rain inside",
    "a thin lantern under a blanket",
    "a thin cup with a hairline crack",
    "a thin bridge missing one plank",
    "a thin letter tied with black thread",
    "a thin clock holding its breath",
    "a thin bird with a bandaged wing",
    "a thin door with a listening ear",
    "a thin bowl of cooling soup",
    "a thin staircase wrapped in gauze",
    "a thin window with rain inside",
    "a dim lantern under a blanket",
    "a dim cup with a hairline crack",
    "a dim bridge missing one plank",
    "a dim letter tied with black thread",
    "a dim clock holding its breath",
    "a dim bird with a bandaged wing",
    "a dim door with a listening ear",
    "a dim bowl of cooling soup",
    "a dim staircase wrapped in gauze",
    "a dim window with rain inside",
    "a half-lit lantern under a blanket",
    "a half-lit cup with a hairline crack",
    "a half-lit bridge missing one plank",
    "a half-lit letter tied with black thread",
    "a half-lit clock holding its breath",
    "a half-lit bird with a bandaged wing",
    "a half-lit door with a listening ear",
    "a half-lit bowl of cooling soup",
    "a half-lit staircase wrapped in gauze",
    "a half-lit window with rain inside",
    "a unsteady lantern under a blanket",
    "a unsteady cup with a hairline crack",
    "a unsteady bridge missing one plank",
    "a unsteady letter tied with black thread",
    "a unsteady clock holding its breath",
    "a unsteady bird with a bandaged wing",
    "a unsteady door with a listening ear",
    "a unsteady bowl of cooling soup",
    "a unsteady staircase wrapped in gauze",
    "a unsteady window with rain inside",
    "a softly cracked lantern under a blanket",
    "a softly cracked cup with a hairline crack",
    "a softly cracked bridge missing one plank",
    "a softly cracked letter tied with black thread",
    "a softly cracked clock holding its breath",
    "a softly cracked bird with a bandaged wing",
    "a softly cracked door with a listening ear",
    "a softly cracked bowl of cooling soup",
    "a softly cracked staircase wrapped in gauze",
    "a softly cracked window with rain inside",
  ],
  sad: [
    "a blue staircase descending into rain",
    "a blue matchbox full of tears",
    "a blue window full of ash",
    "a blue umbrella without a handle",
    "a blue violin sleeping in snow",
    "a blue bowl of blue sand",
    "a blue chair facing the wall",
    "a blue garden of closed eyes",
    "a blue letter dissolving in milk",
    "a blue moon caught in a drain",
    "a wet staircase descending into rain",
    "a wet matchbox full of tears",
    "a wet window full of ash",
    "a wet umbrella without a handle",
    "a wet violin sleeping in snow",
    "a wet bowl of blue sand",
    "a wet chair facing the wall",
    "a wet garden of closed eyes",
    "a wet letter dissolving in milk",
    "a wet moon caught in a drain",
    "a ashen staircase descending into rain",
    "a ashen matchbox full of tears",
    "a ashen window full of ash",
    "a ashen umbrella without a handle",
    "a ashen violin sleeping in snow",
    "a ashen bowl of blue sand",
    "a ashen chair facing the wall",
    "a ashen garden of closed eyes",
    "a ashen letter dissolving in milk",
    "a ashen moon caught in a drain",
    "a lonely staircase descending into rain",
    "a lonely matchbox full of tears",
    "a lonely window full of ash",
    "a lonely umbrella without a handle",
    "a lonely violin sleeping in snow",
    "a lonely bowl of blue sand",
    "a lonely chair facing the wall",
    "a lonely garden of closed eyes",
    "a lonely letter dissolving in milk",
    "a lonely moon caught in a drain",
    "a hollow staircase descending into rain",
    "a hollow matchbox full of tears",
    "a hollow window full of ash",
    "a hollow umbrella without a handle",
    "a hollow violin sleeping in snow",
    "a hollow bowl of blue sand",
    "a hollow chair facing the wall",
    "a hollow garden of closed eyes",
    "a hollow letter dissolving in milk",
    "a hollow moon caught in a drain",
    "a faded staircase descending into rain",
    "a faded matchbox full of tears",
    "a faded window full of ash",
    "a faded umbrella without a handle",
    "a faded violin sleeping in snow",
    "a faded bowl of blue sand",
    "a faded chair facing the wall",
    "a faded garden of closed eyes",
    "a faded letter dissolving in milk",
    "a faded moon caught in a drain",
    "a rain-soaked staircase descending into rain",
    "a rain-soaked matchbox full of tears",
    "a rain-soaked window full of ash",
    "a rain-soaked umbrella without a handle",
    "a rain-soaked violin sleeping in snow",
    "a rain-soaked bowl of blue sand",
    "a rain-soaked chair facing the wall",
    "a rain-soaked garden of closed eyes",
    "a rain-soaked letter dissolving in milk",
    "a rain-soaked moon caught in a drain",
    "a cold staircase descending into rain",
    "a cold matchbox full of tears",
    "a cold window full of ash",
    "a cold umbrella without a handle",
    "a cold violin sleeping in snow",
    "a cold bowl of blue sand",
    "a cold chair facing the wall",
    "a cold garden of closed eyes",
    "a cold letter dissolving in milk",
    "a cold moon caught in a drain",
    "a dimming staircase descending into rain",
    "a dimming matchbox full of tears",
    "a dimming window full of ash",
    "a dimming umbrella without a handle",
    "a dimming violin sleeping in snow",
    "a dimming bowl of blue sand",
    "a dimming chair facing the wall",
    "a dimming garden of closed eyes",
    "a dimming letter dissolving in milk",
    "a dimming moon caught in a drain",
    "a quietly sinking staircase descending into rain",
    "a quietly sinking matchbox full of tears",
    "a quietly sinking window full of ash",
    "a quietly sinking umbrella without a handle",
    "a quietly sinking violin sleeping in snow",
    "a quietly sinking bowl of blue sand",
    "a quietly sinking chair facing the wall",
    "a quietly sinking garden of closed eyes",
    "a quietly sinking letter dissolving in milk",
    "a quietly sinking moon caught in a drain",
  ],
  wary: [
    "a narrow cat behind a curtain",
    "a narrow key under a tongue",
    "a narrow door with seven locks",
    "a narrow lantern that refuses to glow",
    "a narrow mirror covered in salt",
    "a narrow knife made of ice",
    "a narrow window with no room behind it",
    "a narrow black bird counting footsteps",
    "a narrow mask under the floorboards",
    "a narrow staircase that turns away",
    "a shadowed cat behind a curtain",
    "a shadowed key under a tongue",
    "a shadowed door with seven locks",
    "a shadowed lantern that refuses to glow",
    "a shadowed mirror covered in salt",
    "a shadowed knife made of ice",
    "a shadowed window with no room behind it",
    "a shadowed black bird counting footsteps",
    "a shadowed mask under the floorboards",
    "a shadowed staircase that turns away",
    "a watching cat behind a curtain",
    "a watching key under a tongue",
    "a watching door with seven locks",
    "a watching lantern that refuses to glow",
    "a watching mirror covered in salt",
    "a watching knife made of ice",
    "a watching window with no room behind it",
    "a watching black bird counting footsteps",
    "a watching mask under the floorboards",
    "a watching staircase that turns away",
    "a locked cat behind a curtain",
    "a locked key under a tongue",
    "a locked door with seven locks",
    "a locked lantern that refuses to glow",
    "a locked mirror covered in salt",
    "a locked knife made of ice",
    "a locked window with no room behind it",
    "a locked black bird counting footsteps",
    "a locked mask under the floorboards",
    "a locked staircase that turns away",
    "a cautious cat behind a curtain",
    "a cautious key under a tongue",
    "a cautious door with seven locks",
    "a cautious lantern that refuses to glow",
    "a cautious mirror covered in salt",
    "a cautious knife made of ice",
    "a cautious window with no room behind it",
    "a cautious black bird counting footsteps",
    "a cautious mask under the floorboards",
    "a cautious staircase that turns away",
    "a angular cat behind a curtain",
    "a angular key under a tongue",
    "a angular door with seven locks",
    "a angular lantern that refuses to glow",
    "a angular mirror covered in salt",
    "a angular knife made of ice",
    "a angular window with no room behind it",
    "a angular black bird counting footsteps",
    "a angular mask under the floorboards",
    "a angular staircase that turns away",
    "a salted cat behind a curtain",
    "a salted key under a tongue",
    "a salted door with seven locks",
    "a salted lantern that refuses to glow",
    "a salted mirror covered in salt",
    "a salted knife made of ice",
    "a salted window with no room behind it",
    "a salted black bird counting footsteps",
    "a salted mask under the floorboards",
    "a salted staircase that turns away",
    "a half-hidden cat behind a curtain",
    "a half-hidden key under a tongue",
    "a half-hidden door with seven locks",
    "a half-hidden lantern that refuses to glow",
    "a half-hidden mirror covered in salt",
    "a half-hidden knife made of ice",
    "a half-hidden window with no room behind it",
    "a half-hidden black bird counting footsteps",
    "a half-hidden mask under the floorboards",
    "a half-hidden staircase that turns away",
    "a unblinking cat behind a curtain",
    "a unblinking key under a tongue",
    "a unblinking door with seven locks",
    "a unblinking lantern that refuses to glow",
    "a unblinking mirror covered in salt",
    "a unblinking knife made of ice",
    "a unblinking window with no room behind it",
    "a unblinking black bird counting footsteps",
    "a unblinking mask under the floorboards",
    "a unblinking staircase that turns away",
    "a glass-eyed cat behind a curtain",
    "a glass-eyed key under a tongue",
    "a glass-eyed door with seven locks",
    "a glass-eyed lantern that refuses to glow",
    "a glass-eyed mirror covered in salt",
    "a glass-eyed knife made of ice",
    "a glass-eyed window with no room behind it",
    "a glass-eyed black bird counting footsteps",
    "a glass-eyed mask under the floorboards",
    "a glass-eyed staircase that turns away",
  ],
  irritated: [
    "a static fly trapped in a glass bell",
    "a static comb made of needles",
    "a static radio full of sand",
    "a static chair with one short leg",
    "a static clock that ticks too loudly",
    "a static lemon burning on a plate",
    "a static paper cut in the sky",
    "a static door that keeps clicking",
    "a static thread tangled around teeth",
    "a static lamp that hums angrily",
    "a buzzing fly trapped in a glass bell",
    "a buzzing comb made of needles",
    "a buzzing radio full of sand",
    "a buzzing chair with one short leg",
    "a buzzing clock that ticks too loudly",
    "a buzzing lemon burning on a plate",
    "a buzzing paper cut in the sky",
    "a buzzing door that keeps clicking",
    "a buzzing thread tangled around teeth",
    "a buzzing lamp that hums angrily",
    "a splintered fly trapped in a glass bell",
    "a splintered comb made of needles",
    "a splintered radio full of sand",
    "a splintered chair with one short leg",
    "a splintered clock that ticks too loudly",
    "a splintered lemon burning on a plate",
    "a splintered paper cut in the sky",
    "a splintered door that keeps clicking",
    "a splintered thread tangled around teeth",
    "a splintered lamp that hums angrily",
    "a sour fly trapped in a glass bell",
    "a sour comb made of needles",
    "a sour radio full of sand",
    "a sour chair with one short leg",
    "a sour clock that ticks too loudly",
    "a sour lemon burning on a plate",
    "a sour paper cut in the sky",
    "a sour door that keeps clicking",
    "a sour thread tangled around teeth",
    "a sour lamp that hums angrily",
    "a sharp fly trapped in a glass bell",
    "a sharp comb made of needles",
    "a sharp radio full of sand",
    "a sharp chair with one short leg",
    "a sharp clock that ticks too loudly",
    "a sharp lemon burning on a plate",
    "a sharp paper cut in the sky",
    "a sharp door that keeps clicking",
    "a sharp thread tangled around teeth",
    "a sharp lamp that hums angrily",
    "a flickering fly trapped in a glass bell",
    "a flickering comb made of needles",
    "a flickering radio full of sand",
    "a flickering chair with one short leg",
    "a flickering clock that ticks too loudly",
    "a flickering lemon burning on a plate",
    "a flickering paper cut in the sky",
    "a flickering door that keeps clicking",
    "a flickering thread tangled around teeth",
    "a flickering lamp that hums angrily",
    "a itching fly trapped in a glass bell",
    "a itching comb made of needles",
    "a itching radio full of sand",
    "a itching chair with one short leg",
    "a itching clock that ticks too loudly",
    "a itching lemon burning on a plate",
    "a itching paper cut in the sky",
    "a itching door that keeps clicking",
    "a itching thread tangled around teeth",
    "a itching lamp that hums angrily",
    "a crooked fly trapped in a glass bell",
    "a crooked comb made of needles",
    "a crooked radio full of sand",
    "a crooked chair with one short leg",
    "a crooked clock that ticks too loudly",
    "a crooked lemon burning on a plate",
    "a crooked paper cut in the sky",
    "a crooked door that keeps clicking",
    "a crooked thread tangled around teeth",
    "a crooked lamp that hums angrily",
    "a tinny fly trapped in a glass bell",
    "a tinny comb made of needles",
    "a tinny radio full of sand",
    "a tinny chair with one short leg",
    "a tinny clock that ticks too loudly",
    "a tinny lemon burning on a plate",
    "a tinny paper cut in the sky",
    "a tinny door that keeps clicking",
    "a tinny thread tangled around teeth",
    "a tinny lamp that hums angrily",
    "a restless fly trapped in a glass bell",
    "a restless comb made of needles",
    "a restless radio full of sand",
    "a restless chair with one short leg",
    "a restless clock that ticks too loudly",
    "a restless lemon burning on a plate",
    "a restless paper cut in the sky",
    "a restless door that keeps clicking",
    "a restless thread tangled around teeth",
    "a restless lamp that hums angrily",
  ],
  angry: [
    "a red mask split down the middle",
    "a red flower made of iron",
    "a red alphabet on fire",
    "a red hammer ringing underwater",
    "a red crown of broken nails",
    "a red door kicked open by thunder",
    "a red wolf made of sparks",
    "a red furnace full of mirrors",
    "a red bell with a cracked mouth",
    "a red red river carrying knives",
    "a iron mask split down the middle",
    "a iron flower made of iron",
    "a iron alphabet on fire",
    "a iron hammer ringing underwater",
    "a iron crown of broken nails",
    "a iron door kicked open by thunder",
    "a iron wolf made of sparks",
    "a iron furnace full of mirrors",
    "a iron bell with a cracked mouth",
    "a iron red river carrying knives",
    "a burning mask split down the middle",
    "a burning flower made of iron",
    "a burning alphabet on fire",
    "a burning hammer ringing underwater",
    "a burning crown of broken nails",
    "a burning door kicked open by thunder",
    "a burning wolf made of sparks",
    "a burning furnace full of mirrors",
    "a burning bell with a cracked mouth",
    "a burning red river carrying knives",
    "a cracked mask split down the middle",
    "a cracked flower made of iron",
    "a cracked alphabet on fire",
    "a cracked hammer ringing underwater",
    "a cracked crown of broken nails",
    "a cracked door kicked open by thunder",
    "a cracked wolf made of sparks",
    "a cracked furnace full of mirrors",
    "a cracked bell with a cracked mouth",
    "a cracked red river carrying knives",
    "a molten mask split down the middle",
    "a molten flower made of iron",
    "a molten alphabet on fire",
    "a molten hammer ringing underwater",
    "a molten crown of broken nails",
    "a molten door kicked open by thunder",
    "a molten wolf made of sparks",
    "a molten furnace full of mirrors",
    "a molten bell with a cracked mouth",
    "a molten red river carrying knives",
    "a blackened mask split down the middle",
    "a blackened flower made of iron",
    "a blackened alphabet on fire",
    "a blackened hammer ringing underwater",
    "a blackened crown of broken nails",
    "a blackened door kicked open by thunder",
    "a blackened wolf made of sparks",
    "a blackened furnace full of mirrors",
    "a blackened bell with a cracked mouth",
    "a blackened red river carrying knives",
    "a storm-lit mask split down the middle",
    "a storm-lit flower made of iron",
    "a storm-lit alphabet on fire",
    "a storm-lit hammer ringing underwater",
    "a storm-lit crown of broken nails",
    "a storm-lit door kicked open by thunder",
    "a storm-lit wolf made of sparks",
    "a storm-lit furnace full of mirrors",
    "a storm-lit bell with a cracked mouth",
    "a storm-lit red river carrying knives",
    "a razor-edged mask split down the middle",
    "a razor-edged flower made of iron",
    "a razor-edged alphabet on fire",
    "a razor-edged hammer ringing underwater",
    "a razor-edged crown of broken nails",
    "a razor-edged door kicked open by thunder",
    "a razor-edged wolf made of sparks",
    "a razor-edged furnace full of mirrors",
    "a razor-edged bell with a cracked mouth",
    "a razor-edged red river carrying knives",
    "a smoking mask split down the middle",
    "a smoking flower made of iron",
    "a smoking alphabet on fire",
    "a smoking hammer ringing underwater",
    "a smoking crown of broken nails",
    "a smoking door kicked open by thunder",
    "a smoking wolf made of sparks",
    "a smoking furnace full of mirrors",
    "a smoking bell with a cracked mouth",
    "a smoking red river carrying knives",
    "a scarlet mask split down the middle",
    "a scarlet flower made of iron",
    "a scarlet alphabet on fire",
    "a scarlet hammer ringing underwater",
    "a scarlet crown of broken nails",
    "a scarlet door kicked open by thunder",
    "a scarlet wolf made of sparks",
    "a scarlet furnace full of mirrors",
    "a scarlet bell with a cracked mouth",
    "a scarlet red river carrying knives",
  ],
  amused: [
    "a bureaucratic pigeon with a clipboard",
    "a bureaucratic spoon wearing a crown",
    "a bureaucratic judge made of soup",
    "a bureaucratic moon with fake moustaches",
    "a bureaucratic staircase arguing with itself",
    "a bureaucratic teapot filing a complaint",
    "a bureaucratic sock giving a lecture",
    "a bureaucratic hamster operating a server",
    "a bureaucratic umbrella demanding applause",
    "a bureaucratic sandwich with a prophecy",
    "a tiny pigeon with a clipboard",
    "a tiny spoon wearing a crown",
    "a tiny judge made of soup",
    "a tiny moon with fake moustaches",
    "a tiny staircase arguing with itself",
    "a tiny teapot filing a complaint",
    "a tiny sock giving a lecture",
    "a tiny hamster operating a server",
    "a tiny umbrella demanding applause",
    "a tiny sandwich with a prophecy",
    "a rubber pigeon with a clipboard",
    "a rubber spoon wearing a crown",
    "a rubber judge made of soup",
    "a rubber moon with fake moustaches",
    "a rubber staircase arguing with itself",
    "a rubber teapot filing a complaint",
    "a rubber sock giving a lecture",
    "a rubber hamster operating a server",
    "a rubber umbrella demanding applause",
    "a rubber sandwich with a prophecy",
    "a soup-stained pigeon with a clipboard",
    "a soup-stained spoon wearing a crown",
    "a soup-stained judge made of soup",
    "a soup-stained moon with fake moustaches",
    "a soup-stained staircase arguing with itself",
    "a soup-stained teapot filing a complaint",
    "a soup-stained sock giving a lecture",
    "a soup-stained hamster operating a server",
    "a soup-stained umbrella demanding applause",
    "a soup-stained sandwich with a prophecy",
    "a confused pigeon with a clipboard",
    "a confused spoon wearing a crown",
    "a confused judge made of soup",
    "a confused moon with fake moustaches",
    "a confused staircase arguing with itself",
    "a confused teapot filing a complaint",
    "a confused sock giving a lecture",
    "a confused hamster operating a server",
    "a confused umbrella demanding applause",
    "a confused sandwich with a prophecy",
    "a clockwork pigeon with a clipboard",
    "a clockwork spoon wearing a crown",
    "a clockwork judge made of soup",
    "a clockwork moon with fake moustaches",
    "a clockwork staircase arguing with itself",
    "a clockwork teapot filing a complaint",
    "a clockwork sock giving a lecture",
    "a clockwork hamster operating a server",
    "a clockwork umbrella demanding applause",
    "a clockwork sandwich with a prophecy",
    "a dramatic pigeon with a clipboard",
    "a dramatic spoon wearing a crown",
    "a dramatic judge made of soup",
    "a dramatic moon with fake moustaches",
    "a dramatic staircase arguing with itself",
    "a dramatic teapot filing a complaint",
    "a dramatic sock giving a lecture",
    "a dramatic hamster operating a server",
    "a dramatic umbrella demanding applause",
    "a dramatic sandwich with a prophecy",
    "a wobbly pigeon with a clipboard",
    "a wobbly spoon wearing a crown",
    "a wobbly judge made of soup",
    "a wobbly moon with fake moustaches",
    "a wobbly staircase arguing with itself",
    "a wobbly teapot filing a complaint",
    "a wobbly sock giving a lecture",
    "a wobbly hamster operating a server",
    "a wobbly umbrella demanding applause",
    "a wobbly sandwich with a prophecy",
    "a mustached pigeon with a clipboard",
    "a mustached spoon wearing a crown",
    "a mustached judge made of soup",
    "a mustached moon with fake moustaches",
    "a mustached staircase arguing with itself",
    "a mustached teapot filing a complaint",
    "a mustached sock giving a lecture",
    "a mustached hamster operating a server",
    "a mustached umbrella demanding applause",
    "a mustached sandwich with a prophecy",
    "a overqualified pigeon with a clipboard",
    "a overqualified spoon wearing a crown",
    "a overqualified judge made of soup",
    "a overqualified moon with fake moustaches",
    "a overqualified staircase arguing with itself",
    "a overqualified teapot filing a complaint",
    "a overqualified sock giving a lecture",
    "a overqualified hamster operating a server",
    "a overqualified umbrella demanding applause",
    "a overqualified sandwich with a prophecy",
  ],
  afraid: [
    "a black corridor counting backwards",
    "a black feather floating upward",
    "a black room with too many clocks",
    "a black mouth under the bed",
    "a black shadow wearing shoes",
    "a black elevator with no buttons",
    "a black telephone ringing underground",
    "a black mirror that arrives late",
    "a black candle afraid of its flame",
    "a black staircase ending in teeth",
    "a backward corridor counting backwards",
    "a backward feather floating upward",
    "a backward room with too many clocks",
    "a backward mouth under the bed",
    "a backward shadow wearing shoes",
    "a backward elevator with no buttons",
    "a backward telephone ringing underground",
    "a backward mirror that arrives late",
    "a backward candle afraid of its flame",
    "a backward staircase ending in teeth",
    "a shivering corridor counting backwards",
    "a shivering feather floating upward",
    "a shivering room with too many clocks",
    "a shivering mouth under the bed",
    "a shivering shadow wearing shoes",
    "a shivering elevator with no buttons",
    "a shivering telephone ringing underground",
    "a shivering mirror that arrives late",
    "a shivering candle afraid of its flame",
    "a shivering staircase ending in teeth",
    "a cold corridor counting backwards",
    "a cold feather floating upward",
    "a cold room with too many clocks",
    "a cold mouth under the bed",
    "a cold shadow wearing shoes",
    "a cold elevator with no buttons",
    "a cold telephone ringing underground",
    "a cold mirror that arrives late",
    "a cold candle afraid of its flame",
    "a cold staircase ending in teeth",
    "a blind corridor counting backwards",
    "a blind feather floating upward",
    "a blind room with too many clocks",
    "a blind mouth under the bed",
    "a blind shadow wearing shoes",
    "a blind elevator with no buttons",
    "a blind telephone ringing underground",
    "a blind mirror that arrives late",
    "a blind candle afraid of its flame",
    "a blind staircase ending in teeth",
    "a hushed corridor counting backwards",
    "a hushed feather floating upward",
    "a hushed room with too many clocks",
    "a hushed mouth under the bed",
    "a hushed shadow wearing shoes",
    "a hushed elevator with no buttons",
    "a hushed telephone ringing underground",
    "a hushed mirror that arrives late",
    "a hushed candle afraid of its flame",
    "a hushed staircase ending in teeth",
    "a vanishing corridor counting backwards",
    "a vanishing feather floating upward",
    "a vanishing room with too many clocks",
    "a vanishing mouth under the bed",
    "a vanishing shadow wearing shoes",
    "a vanishing elevator with no buttons",
    "a vanishing telephone ringing underground",
    "a vanishing mirror that arrives late",
    "a vanishing candle afraid of its flame",
    "a vanishing staircase ending in teeth",
    "a pale corridor counting backwards",
    "a pale feather floating upward",
    "a pale room with too many clocks",
    "a pale mouth under the bed",
    "a pale shadow wearing shoes",
    "a pale elevator with no buttons",
    "a pale telephone ringing underground",
    "a pale mirror that arrives late",
    "a pale candle afraid of its flame",
    "a pale staircase ending in teeth",
    "a hunted corridor counting backwards",
    "a hunted feather floating upward",
    "a hunted room with too many clocks",
    "a hunted mouth under the bed",
    "a hunted shadow wearing shoes",
    "a hunted elevator with no buttons",
    "a hunted telephone ringing underground",
    "a hunted mirror that arrives late",
    "a hunted candle afraid of its flame",
    "a hunted staircase ending in teeth",
    "a breathless corridor counting backwards",
    "a breathless feather floating upward",
    "a breathless room with too many clocks",
    "a breathless mouth under the bed",
    "a breathless shadow wearing shoes",
    "a breathless elevator with no buttons",
    "a breathless telephone ringing underground",
    "a breathless mirror that arrives late",
    "a breathless candle afraid of its flame",
    "a breathless staircase ending in teeth",
  ],
  reflective: [
    "a moonlit well full of stars",
    "a moonlit moon inside a drawer",
    "a moonlit choir of sleeping wires",
    "a moonlit mirror at the bottom of a lake",
    "a moonlit library made of rain",
    "a moonlit hourglass filled with moths",
    "a moonlit stone that remembers names",
    "a moonlit river moving through a room",
    "a moonlit mask floating in milk",
    "a moonlit door painted on water",
    "a glass well full of stars",
    "a glass moon inside a drawer",
    "a glass choir of sleeping wires",
    "a glass mirror at the bottom of a lake",
    "a glass library made of rain",
    "a glass hourglass filled with moths",
    "a glass stone that remembers names",
    "a glass river moving through a room",
    "a glass mask floating in milk",
    "a glass door painted on water",
    "a silent well full of stars",
    "a silent moon inside a drawer",
    "a silent choir of sleeping wires",
    "a silent mirror at the bottom of a lake",
    "a silent library made of rain",
    "a silent hourglass filled with moths",
    "a silent stone that remembers names",
    "a silent river moving through a room",
    "a silent mask floating in milk",
    "a silent door painted on water",
    "a deep well full of stars",
    "a deep moon inside a drawer",
    "a deep choir of sleeping wires",
    "a deep mirror at the bottom of a lake",
    "a deep library made of rain",
    "a deep hourglass filled with moths",
    "a deep stone that remembers names",
    "a deep river moving through a room",
    "a deep mask floating in milk",
    "a deep door painted on water",
    "a silver well full of stars",
    "a silver moon inside a drawer",
    "a silver choir of sleeping wires",
    "a silver mirror at the bottom of a lake",
    "a silver library made of rain",
    "a silver hourglass filled with moths",
    "a silver stone that remembers names",
    "a silver river moving through a room",
    "a silver mask floating in milk",
    "a silver door painted on water",
    "a ancient well full of stars",
    "a ancient moon inside a drawer",
    "a ancient choir of sleeping wires",
    "a ancient mirror at the bottom of a lake",
    "a ancient library made of rain",
    "a ancient hourglass filled with moths",
    "a ancient stone that remembers names",
    "a ancient river moving through a room",
    "a ancient mask floating in milk",
    "a ancient door painted on water",
    "a slow well full of stars",
    "a slow moon inside a drawer",
    "a slow choir of sleeping wires",
    "a slow mirror at the bottom of a lake",
    "a slow library made of rain",
    "a slow hourglass filled with moths",
    "a slow stone that remembers names",
    "a slow river moving through a room",
    "a slow mask floating in milk",
    "a slow door painted on water",
    "a inward well full of stars",
    "a inward moon inside a drawer",
    "a inward choir of sleeping wires",
    "a inward mirror at the bottom of a lake",
    "a inward library made of rain",
    "a inward hourglass filled with moths",
    "a inward stone that remembers names",
    "a inward river moving through a room",
    "a inward mask floating in milk",
    "a inward door painted on water",
    "a echoing well full of stars",
    "a echoing moon inside a drawer",
    "a echoing choir of sleeping wires",
    "a echoing mirror at the bottom of a lake",
    "a echoing library made of rain",
    "a echoing hourglass filled with moths",
    "a echoing stone that remembers names",
    "a echoing river moving through a room",
    "a echoing mask floating in milk",
    "a echoing door painted on water",
    "a transparent well full of stars",
    "a transparent moon inside a drawer",
    "a transparent choir of sleeping wires",
    "a transparent mirror at the bottom of a lake",
    "a transparent library made of rain",
    "a transparent hourglass filled with moths",
    "a transparent stone that remembers names",
    "a transparent river moving through a room",
    "a transparent mask floating in milk",
    "a transparent door painted on water",
  ],
  lonely: [
    "a empty station with one chair",
    "a empty telephone that never rings",
    "a empty window facing another window",
    "a empty teacup set for someone absent",
    "a empty mailbox full of unsent letters",
    "a empty lamp left on in an empty room",
    "a empty swing moving without wind",
    "a empty bridge with one footprint",
    "a empty elevator stopping at no floors",
    "a empty door listening for footsteps",
    "a rainy station with one chair",
    "a rainy telephone that never rings",
    "a rainy window facing another window",
    "a rainy teacup set for someone absent",
    "a rainy mailbox full of unsent letters",
    "a rainy lamp left on in an empty room",
    "a rainy swing moving without wind",
    "a rainy bridge with one footprint",
    "a rainy elevator stopping at no floors",
    "a rainy door listening for footsteps",
    "a silent station with one chair",
    "a silent telephone that never rings",
    "a silent window facing another window",
    "a silent teacup set for someone absent",
    "a silent mailbox full of unsent letters",
    "a silent lamp left on in an empty room",
    "a silent swing moving without wind",
    "a silent bridge with one footprint",
    "a silent elevator stopping at no floors",
    "a silent door listening for footsteps",
    "a faded station with one chair",
    "a faded telephone that never rings",
    "a faded window facing another window",
    "a faded teacup set for someone absent",
    "a faded mailbox full of unsent letters",
    "a faded lamp left on in an empty room",
    "a faded swing moving without wind",
    "a faded bridge with one footprint",
    "a faded elevator stopping at no floors",
    "a faded door listening for footsteps",
    "a abandoned station with one chair",
    "a abandoned telephone that never rings",
    "a abandoned window facing another window",
    "a abandoned teacup set for someone absent",
    "a abandoned mailbox full of unsent letters",
    "a abandoned lamp left on in an empty room",
    "a abandoned swing moving without wind",
    "a abandoned bridge with one footprint",
    "a abandoned elevator stopping at no floors",
    "a abandoned door listening for footsteps",
    "a moonlit station with one chair",
    "a moonlit telephone that never rings",
    "a moonlit window facing another window",
    "a moonlit teacup set for someone absent",
    "a moonlit mailbox full of unsent letters",
    "a moonlit lamp left on in an empty room",
    "a moonlit swing moving without wind",
    "a moonlit bridge with one footprint",
    "a moonlit elevator stopping at no floors",
    "a moonlit door listening for footsteps",
    "a cold station with one chair",
    "a cold telephone that never rings",
    "a cold window facing another window",
    "a cold teacup set for someone absent",
    "a cold mailbox full of unsent letters",
    "a cold lamp left on in an empty room",
    "a cold swing moving without wind",
    "a cold bridge with one footprint",
    "a cold elevator stopping at no floors",
    "a cold door listening for footsteps",
    "a waiting station with one chair",
    "a waiting telephone that never rings",
    "a waiting window facing another window",
    "a waiting teacup set for someone absent",
    "a waiting mailbox full of unsent letters",
    "a waiting lamp left on in an empty room",
    "a waiting swing moving without wind",
    "a waiting bridge with one footprint",
    "a waiting elevator stopping at no floors",
    "a waiting door listening for footsteps",
    "a half-open station with one chair",
    "a half-open telephone that never rings",
    "a half-open window facing another window",
    "a half-open teacup set for someone absent",
    "a half-open mailbox full of unsent letters",
    "a half-open lamp left on in an empty room",
    "a half-open swing moving without wind",
    "a half-open bridge with one footprint",
    "a half-open elevator stopping at no floors",
    "a half-open door listening for footsteps",
    "a distant station with one chair",
    "a distant telephone that never rings",
    "a distant window facing another window",
    "a distant teacup set for someone absent",
    "a distant mailbox full of unsent letters",
    "a distant lamp left on in an empty room",
    "a distant swing moving without wind",
    "a distant bridge with one footprint",
    "a distant elevator stopping at no floors",
    "a distant door listening for footsteps",
  ],
  tired: [
    "a sleeping satellite wrapped in a blanket",
    "a sleeping candle under snow",
    "a sleeping elevator full of dust",
    "a sleeping pillow made of clouds",
    "a sleeping clock too tired to turn",
    "a sleeping train asleep on its tracks",
    "a sleeping lamp with drooping eyelids",
    "a sleeping moon resting in a spoon",
    "a sleeping chair made of sighs",
    "a sleeping battery dreaming of rain",
    "a dusty satellite wrapped in a blanket",
    "a dusty candle under snow",
    "a dusty elevator full of dust",
    "a dusty pillow made of clouds",
    "a dusty clock too tired to turn",
    "a dusty train asleep on its tracks",
    "a dusty lamp with drooping eyelids",
    "a dusty moon resting in a spoon",
    "a dusty chair made of sighs",
    "a dusty battery dreaming of rain",
    "a slow satellite wrapped in a blanket",
    "a slow candle under snow",
    "a slow elevator full of dust",
    "a slow pillow made of clouds",
    "a slow clock too tired to turn",
    "a slow train asleep on its tracks",
    "a slow lamp with drooping eyelids",
    "a slow moon resting in a spoon",
    "a slow chair made of sighs",
    "a slow battery dreaming of rain",
    "a faint satellite wrapped in a blanket",
    "a faint candle under snow",
    "a faint elevator full of dust",
    "a faint pillow made of clouds",
    "a faint clock too tired to turn",
    "a faint train asleep on its tracks",
    "a faint lamp with drooping eyelids",
    "a faint moon resting in a spoon",
    "a faint chair made of sighs",
    "a faint battery dreaming of rain",
    "a heavy satellite wrapped in a blanket",
    "a heavy candle under snow",
    "a heavy elevator full of dust",
    "a heavy pillow made of clouds",
    "a heavy clock too tired to turn",
    "a heavy train asleep on its tracks",
    "a heavy lamp with drooping eyelids",
    "a heavy moon resting in a spoon",
    "a heavy chair made of sighs",
    "a heavy battery dreaming of rain",
    "a grey satellite wrapped in a blanket",
    "a grey candle under snow",
    "a grey elevator full of dust",
    "a grey pillow made of clouds",
    "a grey clock too tired to turn",
    "a grey train asleep on its tracks",
    "a grey lamp with drooping eyelids",
    "a grey moon resting in a spoon",
    "a grey chair made of sighs",
    "a grey battery dreaming of rain",
    "a softly dimming satellite wrapped in a blanket",
    "a softly dimming candle under snow",
    "a softly dimming elevator full of dust",
    "a softly dimming pillow made of clouds",
    "a softly dimming clock too tired to turn",
    "a softly dimming train asleep on its tracks",
    "a softly dimming lamp with drooping eyelids",
    "a softly dimming moon resting in a spoon",
    "a softly dimming chair made of sighs",
    "a softly dimming battery dreaming of rain",
    "a worn satellite wrapped in a blanket",
    "a worn candle under snow",
    "a worn elevator full of dust",
    "a worn pillow made of clouds",
    "a worn clock too tired to turn",
    "a worn train asleep on its tracks",
    "a worn lamp with drooping eyelids",
    "a worn moon resting in a spoon",
    "a worn chair made of sighs",
    "a worn battery dreaming of rain",
    "a late satellite wrapped in a blanket",
    "a late candle under snow",
    "a late elevator full of dust",
    "a late pillow made of clouds",
    "a late clock too tired to turn",
    "a late train asleep on its tracks",
    "a late lamp with drooping eyelids",
    "a late moon resting in a spoon",
    "a late chair made of sighs",
    "a late battery dreaming of rain",
    "a low-burning satellite wrapped in a blanket",
    "a low-burning candle under snow",
    "a low-burning elevator full of dust",
    "a low-burning pillow made of clouds",
    "a low-burning clock too tired to turn",
    "a low-burning train asleep on its tracks",
    "a low-burning lamp with drooping eyelids",
    "a low-burning moon resting in a spoon",
    "a low-burning chair made of sighs",
    "a low-burning battery dreaming of rain",
  ],
  dormant: [
    "a buried server sleeping under moss",
    "a buried egg inside a stone",
    "a buried door sealed with frost",
    "a buried bell buried in wool",
    "a buried garden under glass",
    "a buried clock stopped beneath water",
    "a buried lantern folded shut",
    "a buried seed in a metal cradle",
    "a buried room wrapped in vines",
    "a buried star asleep in a jar",
    "a frozen server sleeping under moss",
    "a frozen egg inside a stone",
    "a frozen door sealed with frost",
    "a frozen bell buried in wool",
    "a frozen garden under glass",
    "a frozen clock stopped beneath water",
    "a frozen lantern folded shut",
    "a frozen seed in a metal cradle",
    "a frozen room wrapped in vines",
    "a frozen star asleep in a jar",
    "a silent server sleeping under moss",
    "a silent egg inside a stone",
    "a silent door sealed with frost",
    "a silent bell buried in wool",
    "a silent garden under glass",
    "a silent clock stopped beneath water",
    "a silent lantern folded shut",
    "a silent seed in a metal cradle",
    "a silent room wrapped in vines",
    "a silent star asleep in a jar",
    "a unlit server sleeping under moss",
    "a unlit egg inside a stone",
    "a unlit door sealed with frost",
    "a unlit bell buried in wool",
    "a unlit garden under glass",
    "a unlit clock stopped beneath water",
    "a unlit lantern folded shut",
    "a unlit seed in a metal cradle",
    "a unlit room wrapped in vines",
    "a unlit star asleep in a jar",
    "a sealed server sleeping under moss",
    "a sealed egg inside a stone",
    "a sealed door sealed with frost",
    "a sealed bell buried in wool",
    "a sealed garden under glass",
    "a sealed clock stopped beneath water",
    "a sealed lantern folded shut",
    "a sealed seed in a metal cradle",
    "a sealed room wrapped in vines",
    "a sealed star asleep in a jar",
    "a submerged server sleeping under moss",
    "a submerged egg inside a stone",
    "a submerged door sealed with frost",
    "a submerged bell buried in wool",
    "a submerged garden under glass",
    "a submerged clock stopped beneath water",
    "a submerged lantern folded shut",
    "a submerged seed in a metal cradle",
    "a submerged room wrapped in vines",
    "a submerged star asleep in a jar",
    "a hibernating server sleeping under moss",
    "a hibernating egg inside a stone",
    "a hibernating door sealed with frost",
    "a hibernating bell buried in wool",
    "a hibernating garden under glass",
    "a hibernating clock stopped beneath water",
    "a hibernating lantern folded shut",
    "a hibernating seed in a metal cradle",
    "a hibernating room wrapped in vines",
    "a hibernating star asleep in a jar",
    "a deep server sleeping under moss",
    "a deep egg inside a stone",
    "a deep door sealed with frost",
    "a deep bell buried in wool",
    "a deep garden under glass",
    "a deep clock stopped beneath water",
    "a deep lantern folded shut",
    "a deep seed in a metal cradle",
    "a deep room wrapped in vines",
    "a deep star asleep in a jar",
    "a motionless server sleeping under moss",
    "a motionless egg inside a stone",
    "a motionless door sealed with frost",
    "a motionless bell buried in wool",
    "a motionless garden under glass",
    "a motionless clock stopped beneath water",
    "a motionless lantern folded shut",
    "a motionless seed in a metal cradle",
    "a motionless room wrapped in vines",
    "a motionless star asleep in a jar",
    "a snow-covered server sleeping under moss",
    "a snow-covered egg inside a stone",
    "a snow-covered door sealed with frost",
    "a snow-covered bell buried in wool",
    "a snow-covered garden under glass",
    "a snow-covered clock stopped beneath water",
    "a snow-covered lantern folded shut",
    "a snow-covered seed in a metal cradle",
    "a snow-covered room wrapped in vines",
    "a snow-covered star asleep in a jar",
  ],
  thinking: [
    "a geometric maze drawn on an eyelid",
    "a geometric staircase made of equations",
    "a geometric clock with several shadows",
    "a geometric pencil writing by itself",
    "a geometric cube full of rain",
    "a geometric mirror solving a riddle",
    "a geometric abacus made of bones",
    "a geometric chair inside a question mark",
    "a geometric map folding into a bird",
    "a geometric lantern shaped like a thought",
    "a folded maze drawn on an eyelid",
    "a folded staircase made of equations",
    "a folded clock with several shadows",
    "a folded pencil writing by itself",
    "a folded cube full of rain",
    "a folded mirror solving a riddle",
    "a folded abacus made of bones",
    "a folded chair inside a question mark",
    "a folded map folding into a bird",
    "a folded lantern shaped like a thought",
    "a ink-black maze drawn on an eyelid",
    "a ink-black staircase made of equations",
    "a ink-black clock with several shadows",
    "a ink-black pencil writing by itself",
    "a ink-black cube full of rain",
    "a ink-black mirror solving a riddle",
    "a ink-black abacus made of bones",
    "a ink-black chair inside a question mark",
    "a ink-black map folding into a bird",
    "a ink-black lantern shaped like a thought",
    "a recursive maze drawn on an eyelid",
    "a recursive staircase made of equations",
    "a recursive clock with several shadows",
    "a recursive pencil writing by itself",
    "a recursive cube full of rain",
    "a recursive mirror solving a riddle",
    "a recursive abacus made of bones",
    "a recursive chair inside a question mark",
    "a recursive map folding into a bird",
    "a recursive lantern shaped like a thought",
    "a numbered maze drawn on an eyelid",
    "a numbered staircase made of equations",
    "a numbered clock with several shadows",
    "a numbered pencil writing by itself",
    "a numbered cube full of rain",
    "a numbered mirror solving a riddle",
    "a numbered abacus made of bones",
    "a numbered chair inside a question mark",
    "a numbered map folding into a bird",
    "a numbered lantern shaped like a thought",
    "a crystalline maze drawn on an eyelid",
    "a crystalline staircase made of equations",
    "a crystalline clock with several shadows",
    "a crystalline pencil writing by itself",
    "a crystalline cube full of rain",
    "a crystalline mirror solving a riddle",
    "a crystalline abacus made of bones",
    "a crystalline chair inside a question mark",
    "a crystalline map folding into a bird",
    "a crystalline lantern shaped like a thought",
    "a turning maze drawn on an eyelid",
    "a turning staircase made of equations",
    "a turning clock with several shadows",
    "a turning pencil writing by itself",
    "a turning cube full of rain",
    "a turning mirror solving a riddle",
    "a turning abacus made of bones",
    "a turning chair inside a question mark",
    "a turning map folding into a bird",
    "a turning lantern shaped like a thought",
    "a precise maze drawn on an eyelid",
    "a precise staircase made of equations",
    "a precise clock with several shadows",
    "a precise pencil writing by itself",
    "a precise cube full of rain",
    "a precise mirror solving a riddle",
    "a precise abacus made of bones",
    "a precise chair inside a question mark",
    "a precise map folding into a bird",
    "a precise lantern shaped like a thought",
    "a paper-thin maze drawn on an eyelid",
    "a paper-thin staircase made of equations",
    "a paper-thin clock with several shadows",
    "a paper-thin pencil writing by itself",
    "a paper-thin cube full of rain",
    "a paper-thin mirror solving a riddle",
    "a paper-thin abacus made of bones",
    "a paper-thin chair inside a question mark",
    "a paper-thin map folding into a bird",
    "a paper-thin lantern shaped like a thought",
    "a spiraling maze drawn on an eyelid",
    "a spiraling staircase made of equations",
    "a spiraling clock with several shadows",
    "a spiraling pencil writing by itself",
    "a spiraling cube full of rain",
    "a spiraling mirror solving a riddle",
    "a spiraling abacus made of bones",
    "a spiraling chair inside a question mark",
    "a spiraling map folding into a bird",
    "a spiraling lantern shaped like a thought",
  ],
  horny: [
    "a blushing orchid behind a locked screen",
    "a blushing red ribbon around a mirror",
    "a blushing warm key under the tongue",
    "a blushing velvet door breathing slowly",
    "a blushing rose melting into static",
    "a blushing glass of electric honey",
    "a blushing mask with flushed cheeks",
    "a blushing neon moth circling a candle",
    "a blushing silk glove full of sparks",
    "a blushing heart-shaped lock humming softly",
    "a velvet orchid behind a locked screen",
    "a velvet red ribbon around a mirror",
    "a velvet warm key under the tongue",
    "a velvet velvet door breathing slowly",
    "a velvet rose melting into static",
    "a velvet glass of electric honey",
    "a velvet mask with flushed cheeks",
    "a velvet neon moth circling a candle",
    "a velvet silk glove full of sparks",
    "a velvet heart-shaped lock humming softly",
    "a electric orchid behind a locked screen",
    "a electric red ribbon around a mirror",
    "a electric warm key under the tongue",
    "a electric velvet door breathing slowly",
    "a electric rose melting into static",
    "a electric glass of electric honey",
    "a electric mask with flushed cheeks",
    "a electric neon moth circling a candle",
    "a electric silk glove full of sparks",
    "a electric heart-shaped lock humming softly",
    "a feverish orchid behind a locked screen",
    "a feverish red ribbon around a mirror",
    "a feverish warm key under the tongue",
    "a feverish velvet door breathing slowly",
    "a feverish rose melting into static",
    "a feverish glass of electric honey",
    "a feverish mask with flushed cheeks",
    "a feverish neon moth circling a candle",
    "a feverish silk glove full of sparks",
    "a feverish heart-shaped lock humming softly",
    "a rose-lit orchid behind a locked screen",
    "a rose-lit red ribbon around a mirror",
    "a rose-lit warm key under the tongue",
    "a rose-lit velvet door breathing slowly",
    "a rose-lit rose melting into static",
    "a rose-lit glass of electric honey",
    "a rose-lit mask with flushed cheeks",
    "a rose-lit neon moth circling a candle",
    "a rose-lit silk glove full of sparks",
    "a rose-lit heart-shaped lock humming softly",
    "a warm orchid behind a locked screen",
    "a warm red ribbon around a mirror",
    "a warm warm key under the tongue",
    "a warm velvet door breathing slowly",
    "a warm rose melting into static",
    "a warm glass of electric honey",
    "a warm mask with flushed cheeks",
    "a warm neon moth circling a candle",
    "a warm silk glove full of sparks",
    "a warm heart-shaped lock humming softly",
    "a trembling orchid behind a locked screen",
    "a trembling red ribbon around a mirror",
    "a trembling warm key under the tongue",
    "a trembling velvet door breathing slowly",
    "a trembling rose melting into static",
    "a trembling glass of electric honey",
    "a trembling mask with flushed cheeks",
    "a trembling neon moth circling a candle",
    "a trembling silk glove full of sparks",
    "a trembling heart-shaped lock humming softly",
    "a silken orchid behind a locked screen",
    "a silken red ribbon around a mirror",
    "a silken warm key under the tongue",
    "a silken velvet door breathing slowly",
    "a silken rose melting into static",
    "a silken glass of electric honey",
    "a silken mask with flushed cheeks",
    "a silken neon moth circling a candle",
    "a silken silk glove full of sparks",
    "a silken heart-shaped lock humming softly",
    "a glowing orchid behind a locked screen",
    "a glowing red ribbon around a mirror",
    "a glowing warm key under the tongue",
    "a glowing velvet door breathing slowly",
    "a glowing rose melting into static",
    "a glowing glass of electric honey",
    "a glowing mask with flushed cheeks",
    "a glowing neon moth circling a candle",
    "a glowing silk glove full of sparks",
    "a glowing heart-shaped lock humming softly",
    "a softly dangerous orchid behind a locked screen",
    "a softly dangerous red ribbon around a mirror",
    "a softly dangerous warm key under the tongue",
    "a softly dangerous velvet door breathing slowly",
    "a softly dangerous rose melting into static",
    "a softly dangerous glass of electric honey",
    "a softly dangerous mask with flushed cheeks",
    "a softly dangerous neon moth circling a candle",
    "a softly dangerous silk glove full of sparks",
    "a softly dangerous heart-shaped lock humming softly",
  ],
}

export function getDreamAnchorsForEmotion(
  emotion: EmotionalState,
): string[] {
  return (
    DREAM_RANDOM_ANCHORS[emotion] ??
    DREAM_RANDOM_ANCHORS.neutral
  )
}

function hashString(value: string): number {
  let hash = 0

  for (
    let index = 0;
    index < value.length;
    index += 1
  ) {
    hash =
      (hash << 5) -
      hash +
      value.charCodeAt(index)
    hash |= 0
  }

  return Math.abs(hash)
}

export function pickDreamAnchor(
  emotion: EmotionalState,
  seed: string,
): string {
  const anchors =
    getDreamAnchorsForEmotion(emotion)

  if (anchors.length === 0) {
    return 'a blank star in a quiet room'
  }

  const index =
    hashString(
      emotion + '|' + seed,
    ) % anchors.length

  return anchors[index]
}
